import json

# s = '```json\n{\n  "attacks": [\n    {\n      "attack_type": "Port Scanning",\n      "confidence": 90,\n      "description": "Single IP (192.168.117.1) is attempting to connect to multiple ports on the target IP (192.168.117.130) with a high rate of packets.",\n      "evidence": {\n        "source_ip": "192.168.117.1",\n        "target_ip": "192.168.117.130",\n        "number_of_packets": 51,\n        "ports_scanned": [80, 443, 21]\n      },\n      "recommendations": "Enable port filtering and monitor for suspicious port activity.",\n      "severity": "MEDIUM"\n    },\n    {\n      "attack_type": "Address Scanning",\n      "confidence": 85,\n      "description": "Single IP (192.168.117.1) is attempting to connect to multiple target IPs (192.168.117.130) with a high rate of packets.",\n      "evidence": {\n        "source_ip": "192.168.117.1",\n        "target_ip": ["192.168.117.130", "192.168.117.140", "192.168.117.150"],\n        "number_of_packets": 51\n      },\n      "recommendations": "Implement address filtering and monitor for suspicious address activity.",\n      "severity": "MEDIUM"\n    },\n    {\n      "attack_type": "SYN Flood",\n      "confidence": 95,\n      "description："A large number of SYN packets (51) are being sent to the target IP (192.168.117.130) within a short period of time, potentially causing a denial of service (DoS) attack.",\n      "evidence": {\n        "source_ip": "192.168.117.1",\n        "target_ip": "192.168.117.130",\n        "type_of_packet": "SYN",\n        "number_of_packets": 51\n      },\n      "recommendations": "Enable rate limiting and monitor for SYN flood attacks.",\n      "severity": "HIGH"\n    },\n    {\n      "attack_type": "UDP Flood",\n      "confidence": 80,\n      "description："A large number of UDP packets (51) are being sent to the target IP (192.168.117.130) within a short period of time, potentially causing a denial of service (DoS) attack.",\n      "evidence": {\n        "source_ip": "192.168.117.1",\n        "target_ip": "192.168.117.130",\n        "type_of_packet": "UDP",\n        "number_of_packets": 51\n      },\n      "recommendations": "Enable rate limiting and monitor for UDP flood attacks.",\n      "severity": "HIGH"\n    },\n    {\n      "attack_type": "ICMP Flood",\n      "confidence": 80,\n      "description："A large number of ICMP packets (51) are being sent to the target IP (192.168.117.130) within a short period of time, potentially causing a denial of service (DoS) attack.",\n      "evidence": {\n        "source_ip": "192.168.117.1",\n        "target_ip": "192.168.117.130",\n        "type_of_packet": "ICMP",\n        "number_of_packets": 51\n      },\n      "recommendations": "Enable rate limiting and monitor for ICMP flood attacks.",\n      "severity": "HIGH"\n    }\n  ]\n}\n```'

# # 移除代码块的标记
# json_str = s.replace('```json\n', '').replace('```', '')
# json_str = json_str.replace('：', '":')# 修正中文冒号

json_str = '{\n  "attacks": [\n    {\n      "attack_type": "Port Scanning",\n      "confidence": 90,\n      "description": "Single IP (192.168.117.1) is attempting to connect to multiple ports on the target IP (192.168.117.130) with a high rate of packets.",\n      "evidence": {\n        "source_ip": "192.168.117.1",\n        "target_ip": "192.168.117.130",\n        "number_of_connections": 51,\n        "port_range": [80, 81, 82, 83, 84, 85]\n      },\n      "recommendations": "Enable port filtering and monitor for suspicious port activity.",\n      "severity": "MEDIUM"\n    },\n    {\n      "attack_type": "Address Scanning",\n      "confidence": 85,\n      "description": "Single IP (192.168.117.1) is attempting to connect to multiple target IPs (192.168.117.130) with a high rate of packets.",\n      "evidence": {\n        "source_ip": "192.168.117.1",\n        "target_ip": ["192.168.117.130", "192.168.117.140", "192.168.117.150"],\n        "number_of_connections": 51\n      },\n      "recommendations": "Implement address filtering and monitor for suspicious address activity.",\n      "severity": "MEDIUM"\n    },\n    {\n      "attack_type": "SYN Flood",\n      "confidence": 95,\n      "description":"A large number of SYN packets (51) are being sent to the target IP (192.168.117.130) within a short period of time, potentially causing a denial of service (DoS) attack.",\n      "evidence": {\n        "source_ip": "192.168.117.1",\n        "target_ip": "192.168.117.130",\n        "type_of_attack": "SYN Flood",\n        "number_of_packets": 51\n      },\n      "recommendations": "Enable rate limiting and configure firewalls to prevent SYN Flood attacks.",\n      "severity": "HIGH"\n    },\n    {\n      "attack_type": "UDP Flood",\n      "confidence": 80,\n      "description":"A large number of UDP packets (51) are being sent to the target IP (192.168.117.130) within a short period of time, potentially causing a denial of service (DoS) attack.",\n      "evidence": {\n        "source_ip": "192.168.117.1",\n        "target_ip": "192.168.117.130",\n        "type_of_attack": "UDP Flood",\n        "number_of_packets": 51\n      },\n      "recommendations": "Enable rate limiting and configure firewalls to prevent UDP Flood attacks.",\n      "severity": "HIGH"\n    },\n    {\n      "attack_type": "ICMP Flood",\n      "confidence": 80,\n      "description":"A large number of ICMP packets (51) are being sent to the target IP (192.168.117.130) within a short period of time, potentially causing a denial of service (DoS) attack.",\n      "evidence": {\n        "source_ip": "192.168.117.1",\n        "target_ip": "192.168.117.130",\n        "type_of_attack": "ICMP Flood",\n        "number_of_packets": 51\n      },\n      "recommendations": "Enable rate limiting and configure firewalls to prevent ICMP Flood attacks.",\n      "severity": "HIGH"\n    }\n  ]\n}\n'
# 解析JSON字符串
data = json.loads(json_str)

# 获取前四个攻击记录
attacks = data['attacks']

# 打印结果
print("attacks列表包含", len(attacks), "个字典:")
for i, attack in enumerate(attacks, 1):
    print(f"\n{i}. {attack['attack_type']}")
    print(f"   严重性: {attack['severity']}")
    print(f"   置信度: {attack['confidence']}%")